_homepage:
    pattern:  /
    defaults: { _controller: AcmeMainBundle:Default:index }

_articles:
    pattern:  /kolumne
    defaults: { _controller: AcmeMainBundle:Default:articles }

_articleSingle:
    pattern:  /kolumne-single
    defaults: { _controller: AcmeMainBundle:Default:articleSingle }

_events:
    pattern:  /dogodki
    defaults: { _controller: AcmeMainBundle:Default:events }

_forum:
    pattern:  /forum
    defaults: { _controller: AcmeMainBundle:Default:forum }

_jobs:
    pattern:  /borza-dela
    defaults: { _controller: AcmeMainBundle:Default:jobs }

_projects:
    pattern:  /projekti
    defaults: { _controller: AcmeMainBundle:Default:projects }

_tutorials:
    pattern:  /vodici
    defaults: { _controller: AcmeMainBundle:Default:tutorials }

_tutorialSingle:
    pattern:  /vodici-single
    defaults: { _controller: AcmeMainBundle:Default:tutorialSingle }

_admin:
    pattern:  /admin
    defaults: { _controller: AcmeMainBundle:Default:admin }

_news:
    pattern:  /novice
    defaults: { _controller: AcmeMainBundle:Default:news }

_newsSingle:
    pattern:  /novice-single
    defaults: { _controller: AcmeMainBundle:Default:newsSingle }

_irc:
    pattern:  /irc
    defaults: { _controller: AcmeMainBundle:Default:irc }