_homepage:
    pattern:  /
    defaults: { _controller: AcmeMainBundle:Default:index }

_articles:
    pattern:  /kolumne
    defaults: { _controller: AcmeMainBundle:Default:articles }

_events:
    pattern:  /dogodki
    defaults: { _controller: AcmeMainBundle:Default:events }

_forum:
    pattern:  /forum
    defaults: { _controller: AcmeMainBundle:Default:forum }

_jobs:
    pattern:  /borza-dela
    defaults: { _controller: AcmeMainBundle:Default:jobs }

_projects:
    pattern:  /projekti
    defaults: { _controller: AcmeMainBundle:Default:projects }

_tutorials:
    pattern:  /vodici
    defaults: { _controller: AcmeMainBundle:Default:tutorials }

_admin:
    pattern:  /admin
    defaults: { _controller: AcmeMainBundle:Default:admin }

_articles:
    pattern:  /novice
    defaults: { _controller: AcmeMainBundle:Default:news }